### PR TITLE
Add fork sync

### PR DESCRIPTION
**Pull request by jonesbusy**
Add fork sync

Ensure existing forks are sync with upstream

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jonesbusy** [comment]
Depends on https://github.com/hub4j/github-api/pull/1898

**Comment by jonesbusy** [comment]
Rebased this PR

**Comment by jonesbusy** [comment]
Finally it's realeased! Ready for review

**Review by gounthar — APPROVED** [review]
Thanks for your commitment!

**Pull request merged**
