### PR TITLE
Update root dockerfile with sdkman

### PR DESCRIPTION
**Pull request by jonesbusy**
To be honnest I'm not sure how to test this. 

```
updatecli diff --config updatecli/updatecli.d --values updatecli/values.github-action.yaml
```

But this give me errors on target

```
        ✔ [JDK17] Get the latest JDK17 version from SDKMAN
        ✔ [JDK21] Get the latest JDK21 version from SDKMAN
        ✔ [JDK8] Get the latest JDK8 version from SDKMAN
Target:
        ✗ [setJDK11] [Dockerfile] Update the JDK11 version for SDKMAN
        ✗ [setJDK11InProperties] [sdkman.properties] Update the JDK11 version
        ✗ [setJDK17] [Dockerfile] Update the JDK17 version for SDKMAN
        ✗ [setJDK17InProperties] [sdkman.properties] Update the JDK17 version
```

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by gounthar** [comment]
I guess that's because the `ENV` instruction you're trying to change does not exist yet in the `main` branch.
Most of the time, I create two PRs when I want to change something in a `updatecli` manifest.

The first PR will contain the changes in the target (or condition) files, and the second PR will change the manifest once the first PR is merged.

You can also target locally another branch thanks to the `updatecli` values file where the changes would already be, or even change the repo owner when you do your tests.
The only thing to remember is not to commit the `updatecli` values with your other changes. 🤷

**Comment by jonesbusy** [comment]
Hey, thanks for the tips. I will try next time.

The point is that I don't get the same errors on my machine than the pipeline

Here is clear to me 

```
ERROR: something went wrong in target "setJDK8" : "✗ No line found matching the keyword \"ENV\" and the matcher \"JDK8_PACKAGE\"."
```

In the meanwhile I will merge this PR and check the action again

**Comment by jonesbusy** [comment]
Seems to work https://github.com/jenkinsci/plugin-modernizer-tool/actions/runs/10650747987/job/29522492909

**Review by gounthar — APPROVED** [review]
Great news!

**Pull request merged**
